project:
  type: website
  output-dir: docs

website:
  title: "Musharraf Mir Akhmadova"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.pdf
        text: Resume
      - text: Assignments
        menu:
        - href: assign01.qmd
          text: Assignment 1
        - href: assign02.qmd
          text: Assignment 2
        - href: assign03.qmd
          text: Assignment 3
        - href: assign04.qmd
          text: Assignment 4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

