project:
  type: website

website:
  title: "Musharraf Mir Akhmadova"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.pdf
        text: Resume
      - text: Assignments
        menu:
        - href: assign01.qmd
          text: Assignment 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

